"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var aluno_1 = require("../aluno");
var a1 = new aluno_1.default(9.7);
var a2 = new aluno_1.default(8.3);
var a3 = new aluno_1.default(7.2);
var a4 = new aluno_1.default(6.9);
var a5 = new aluno_1.default(4);
var a6 = new aluno_1.default(1000);
console.log(a1.toString());
console.log(a2.toString());
console.log(a3.toString());
console.log(a4.toString());
console.log(a5.toString());
console.log(a6.toString());
